language: python

cache:
  directories:
    - $HOME/.cache/pip

sudo: false

install:
  - pip install --upgrade --requirement requirements-ci.txt

script:
  - git diff --check $TRAVIS_COMMIT_RANGE --
  - flake8 temboard temboardui
  - py.test -vv --showlocals --strict --full-trace test/
