language: python

cache:
  directories:
    - $HOME/.cache/pip

sudo: false

install:
  - pip install flake8 flake8-diff

script:
  - git diff --check $TRAVIS_COMMIT_RANGE
  - flake8-diff $TRAVIS_COMMIT_RANGE
