language: python

cache:
  directories:
    - $HOME/.cache/pip

sudo: false

install:
  - pip install flake8 flake8-diff pytest
  - pip install -e .

script:
  - git diff --check $TRAVIS_COMMIT_RANGE
  - flake8-diff $TRAVIS_COMMIT_RANGE
  - py.test -vv --showlocals --strict --full-trace test/
