site_name: temBoard
site_description: PostgreSQL Remote Control
site_author: www.dalibo.com
copyright: Copyright 2015-2017 <a href="http://www.dalibo.com">dalibo</a>
repo_url: https://github.com/dalibo/temboard/tree/master/doc
docs_dir: doc
theme: readthedocs
pages:
- Home: index.md
- Quick Start: QUICKSTART.md
- Installation:
  - Overview: installation.md
  - Server Installation: temboard-install-sources.md
  - Repository Setup: temboard-repository-setup.md
- How To: temboard-howto.md

# Markdown settings
strict: yes
markdown_extensions:
- toc:
    baselevel: 2
    permalink: yes
