site_name: temBoard
site_description: PostgreSQL Remote Control
site_author: www.dalibo.com
copyright: Copyright 2015-2017 <a href="http://www.dalibo.com">dalibo</a>
repo_url: https://github.com/dalibo/temboard/tree/master/doc
theme:
- name: readthedocs
pages:
- Home: index.md
- Quick Start: QUICKSTART.md
- Installation:
  - Overview: installation.md
  - Server installation from sources: temboard-install-sources.md
  - Server installation from RPM: temboard-install-rpm.md
  - Repository setup: temboard-repository-setup.md
  - Upgrade 1.2 to 2.0 (RHEL/CentOS): temboard-upgrade-1.2-2.0.md
  - Upgrade 1.1 to 1.2 (RHEL/CentOS): temboard-upgrade-1.1-1.2.md
  - Upgrade 0.0.1 to 1.1 (RHEL/CentOS): temboard-upgrade-0.0.1-1.1.md
- How To:
  - temBoard UI howto: temboard-howto.md
  - Alerting: temboard-howto-alerting.md

# Markdown settings
strict: yes
markdown_extensions:
- toc:
    baselevel: 2
    permalink: yes
