version: 2

jobs:
  0-doc:
    docker: [{image: "python:3.5"}]
    working_directory: ~/project
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        name: Build documentation with mkdocs
        command: |
          pip install --upgrade --requirement docs/requirements.txt
          mkdocs
    - store_artifacts:
        path: README.html
        destination: build/README.html

  0-unit:
    docker: [{image: "python:2.7"}]
    working_directory: /workspace
    steps:
      - checkout
      - run: git submodule update --init
      - &pip-cache-restore
        restore_cache:
          keys:
            - temboard-{{ .Branch }}
            - temboard-master
      - run:
          name: Setup python environment
          command: |
            pip2.7 install --upgrade --requirement requirements-ci.txt --editable .
      - run:
          name: Lint
          command: |
            # See https://discuss.circleci.com/t/commit-range-environment-variable/10410
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8
            python2.7 setup.py --long-description | rst2html.py --verbose --halt=warning - >/dev/null
      - run:
          name: Python tests
          command: |
            pytest --full-trace --cov-report=xml tests/unit/
      - &pip-cache-save
        save_cache:
          key: temboard-{{ .Branch }}
          paths: ["~/.cache/pip/"]

  0-rpm-centos7:
    docker: [{image: "rpmbuild/centos7"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        name: Build RPM snapshot
        command: |
          sudo yum-builddep -y packaging/rpm/temboard.spec
          python setup.py sdist
          VERSION=$(python setup.py --version) packaging/rpm/build.sh
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths:
        - dist/rpm/noarch/*.rpm

  0-deb-stretch:
    docker: [{image: "dalibo/temboard-agent-sdk:stretch"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        command: ./packaging/deb/mkdeb.sh
        environment:
          DEBFULLNAME: CircleCI
          DEBEMAIL: none@example.com
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths: [dist/*.deb]

  1-func-stretch:
    docker:
    - &func-temboard
      image: dalibo/temboard-agent-sdk:stretch
      environment:
        PGHOST: 0.0.0.0
        PGUSER: temboard
        PGPASSWORD: &PGPASSWORD confidentiel
        SELENIUM: http://0.0.0.0:4444
        TEMBOARD_PASSWORD: *PGPASSWORD
    - &func-postgres
      image: postgres:10-alpine
      environment:
        POSTGRES_USER: temboard
        POSTGRES_PASSWORD: *PGPASSWORD
    - &func-selenium
      image: selenium/standalone-firefox
    steps: &func-steps
    - checkout
    - run: git submodule update --init
    - *pip-cache-restore
    - run:
        name: Setup
        command: |
            pip2.7 install --upgrade --editable .
            pip2.7 install --upgrade --requirement tests/func/requirements.txt
    - run:
        name: Functionnal tests
        command: tests/func/run.sh
    - *pip-cache-save

  1-func-centos7:
    docker:
    - <<: *func-temboard
      image: dalibo/temboard-agent-sdk:centos7
    - *func-postgres
    - *func-selenium
    steps: *func-steps


workflows:
  version: 2
  pipeline:
    jobs:
    - 0-doc
    - 0-unit
    - 0-rpm-centos7
    - 0-deb-stretch
    - 1-func-stretch:
        requires: [0-unit]
    - 1-func-centos7:
        requires: [0-unit]
