version: 2

jobs:
  0-doc:
    docker: [{image: "python:3.5"}]
    working_directory: ~/project
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        name: Build documentation with mkdocs
        command: |
          pip install --upgrade --requirement docs/requirements.txt
          mkdocs
    - store_artifacts:
        path: README.html
        destination: build/README.html

  0-lint:
    docker: [{image: "python:2.7"}]
    working_directory: /workspace
    steps:
      - checkout
      - &restore_cache
        restore_cache:
          keys:
            - temboard-{{ .Branch }}
            - temboard-master
      - &python_setup
        run:
          name: Setup python environment
          command: |
            pip install --upgrade --requirement requirements-ci.txt --editable .

      - run:
          name: Lint
          command: |
            # See https://discuss.circleci.com/t/commit-range-environment-variable/10410
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 temboard temboardui
            python setup.py --long-description | rst2html.py --verbose --halt=warning - >/dev/null
      - &save_cache
        save_cache:
          key: temboard-{{ .Branch }}
          paths: ["~/.cache/pip/"]

  0-rpm-centos7:
    docker: [{image: "rpmbuild/centos7"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        name: Build RPM snapshot
        command: |
          sudo yum-builddep -y packaging/rpm/temboard.spec
          python setup.py sdist
          VERSION=$(python setup.py --version) packaging/rpm/build.sh
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths:
        - dist/rpm/noarch/*.rpm

  0-unit:
    docker: [{image: "python:2.7"}]
    working_directory: /workspace
    steps:
      - checkout
      - run: git submodule update --init
      - *restore_cache
      - *python_setup
      - run:
          name: Python tests
          command: |
            pytest --full-trace --cov-report=xml tests/unit/
            codecov
      - *save_cache

  1-deb-stretch:
    docker: [{image: "dalibo/temboard-agent-sdk:stretch"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        command: ./packaging/deb/mkdeb.sh
        environment:
          DEBFULLNAME: CircleCI
          DEBEMAIL: none@example.com
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths: [dist/*.deb]


workflows:
  version: 2
  pipeline:
    jobs:
    - 0-doc
    - 0-lint
    - 0-rpm-centos7
    - 0-unit
    - 1-deb-stretch
