version: '3'

services:
  stretch: &mkdeb
    image: dalibo/temboard-agent-sdk:stretch
    environment:
      # See dch(1)
      DEBFULLNAME: ${DEBFULLNAME}
      DEBEMAIL: ${DEBEMAIL}
      VERSION: "${VERSION-}"
    volumes:
    - ../..:/workspace
    command: /workspace/packaging/deb/mkdeb.sh

  jessie:
    <<: *mkdeb
    image: dalibo/temboard-agent-sdk:jessie
