version: '2'

services:
  buster: &mkdeb
    image: dalibo/temboard-agent-sdk:buster
    environment:
      # See dch(1)
      DEBFULLNAME: ${DEBFULLNAME}
      DEBEMAIL: ${DEBEMAIL}
    volumes:
    - ../..:/workspace
    command: /workspace/packaging/deb/mkdeb.sh

  stretch:
    <<: *mkdeb
    image: dalibo/temboard-agent-sdk:stretch

  jessie:
    <<: *mkdeb
    image: dalibo/temboard-agent-sdk:jessie
